zinnia/models.py
"""Models of Zinnia"""
import warnings
from datetime import datetime

from django.db import models
from django.db.models import Q
from django.utils.html import strip_tags
from django.utils.html import linebreaks
from django.contrib.auth.models import User
from django.contrib.sites.models import Site
from django.db.models.signals import post_save
from django.utils.importlib import import_module
from django.contrib.comments.models import Comment
from django.contrib.comments.models import CommentFlag
from django.contrib.comments.moderation import moderator
from django.utils.translation import ugettext_lazy as _

from django.contrib.markup.templatetags.markup import markdown
from django.contrib.markup.templatetags.markup import textile
from django.contrib.markup.templatetags.markup import restructuredtext

import mptt
from tagging.fields import TagField

from zinnia.settings import UPLOAD_TO
from zinnia.settings import MARKUP_LANGUAGE
from zinnia.settings import ENTRY_TEMPLATES
from zinnia.settings import ENTRY_BASE_MODEL
from zinnia.settings import MARKDOWN_EXTENSIONS
from zinnia.settings import AUTO_CLOSE_COMMENTS_AFTER
from zinnia.managers import entries_published
from zinnia.managers import EntryPublishedManager
from zinnia.managers import AuthorPublishedManager
from zinnia.managers import DRAFT, HIDDEN, PUBLISHED
from zinnia.moderator import EntryCommentModerator
from zinnia.url_shortener import get_url_shortener
from zinnia.signals import ping_directories_handler
from zinnia.signals import ping_external_urls_handler


class Author(User):
    """Proxy Model around User"""

    objects = models.Manager()
    published = AuthorPublishedManager()

    def entries_published_set(self):
        """Return only the entries published"""
        return entries_published(self.entry_set)

    @models.permalink
    def get_absolute_url(self):
        """Return author's URL"""
        return ('zinnia_author_detail', (self.username,))

    class Meta:
        """Author's Meta"""
        proxy = True


class Category(models.Model):
    """Category object for Entry"""

    title = models.CharField(_('title'), max_length=255)
    slug = models.SlugField(help_text=_('used for publication'),
                            unique=True, max_length=255)
    description = models.TextField(_('description'), blank=True)

    parent = models.ForeignKey('self', null=True, blank=True,
                               verbose_name=_('parent category'),
                               related_name='children')

    def entries_published_set(self):
        """Return only the entries published"""
        return entries_published(self.entry_set)

    @property
    def tree_path(self):
        """Return category's tree path, by his ancestors"""
        if self.parent:
            return '%s/%s' % (self.parent.tree_path, self.slug)
        return self.slug

    def __unicode__(self):
        return self.title

    @models.permalink
    def get_absolute_url(self):
        """Return category's URL"""
        return ('zinnia_category_detail', (self.tree_path,))

    class Meta:
        """Category's Meta"""
        ordering = ['title']
        verbose_name = _('category')
        verbose_name_plural = _('categories')


class EntryAbstractClass(models.Model):
    """Base Model design for publishing entries"""
    STATUS_CHOICES = ((DRAFT, _('draft')),
                      (HIDDEN, _('hidden')),
                      (PUBLISHED, _('published')))

    title = models.CharField(_('title'), max_length=255)

    image = models.ImageField(_('image'), upload_to=UPLOAD_TO,
                              blank=True, help_text=_('used for illustration'))
    content = models.TextField(_('content'))
    excerpt = models.TextField(_('excerpt'), blank=True,
                                help_text=_('optional element'))

    tags = TagField(_('tags'))
    categories = models.ManyToManyField(Category, verbose_name=_('categories'),
                                        blank=True, null=True)
    related = models.ManyToManyField('self', verbose_name=_('related entries'),
                                     blank=True, null=True)

    slug = models.SlugField(help_text=_('used for publication'),
                            unique_for_date='creation_date',
                            max_length=255)

    authors = models.ManyToManyField(User, verbose_name=_('authors'),
                                     blank=True, null=False)
    status = models.IntegerField(choices=STATUS_CHOICES, default=DRAFT)
    featured = models.BooleanField(_('featured'), default=False)
    comment_enabled = models.BooleanField(_('comment enabled'), default=True)
    pingback_enabled = models.BooleanField(_('linkback enabled'), default=True)

    creation_date = models.DateTimeField(_('creation date'),
                                         default=datetime.now)
    last_update = models.DateTimeField(_('last update'), default=datetime.now)
    start_publication = models.DateTimeField(_('start publication'),
                                             help_text=_('date start publish'),
                                             default=datetime.now)
    end_publication = models.DateTimeField(_('end publication'),
                                           help_text=_('date end publish'),
                                           default=datetime(2042, 3, 15))

    sites = models.ManyToManyField(Site, verbose_name=_('sites publication'))

    login_required = models.BooleanField(
        _('login required'), default=False,
        help_text=_('only authenticated users can view the entry'))
    password = models.CharField(
        _('password'), max_length=50, blank=True,
        help_text=_('protect the entry with a password'))

    template = models.CharField(
        _('template'), max_length=250,
        default='zinnia/entry_detail.html',
        choices=[('zinnia/entry_detail.html', _('Default template'))] + \
        ENTRY_TEMPLATES,
        help_text=_('template used to display the entry'))

    objects = models.Manager()
    published = EntryPublishedManager()

    @property
    def html_content(self):
        """Return the content correctly formatted"""
        if MARKUP_LANGUAGE == 'markdown':
            return markdown(self.content, MARKDOWN_EXTENSIONS)
        elif MARKUP_LANGUAGE == 'textile':
            return textile(self.content)
        elif MARKUP_LANGUAGE == 'restructuredtext':
            return restructuredtext(self.content)
        elif not '</p>' in self.content:
            return linebreaks(self.content)
        return self.content

    @property
    def previous_entry(self):
        """Return the previous entry"""
        entries = Entry.published.filter(
            creation_date__lt=self.creation_date)[:1]
        if entries:
            return entries[0]

    @property
    def next_entry(self):
        """Return the next entry"""
        entries = Entry.published.filter(
            creation_date__gt=self.creation_date).order_by('creation_date')[:1]
        if entries:
            return entries[0]

    @property
    def word_count(self):
        """Count the words of an entry"""
        return len(strip_tags(self.html_content).split())

    @property
    def is_actual(self):
        """Check if an entry is within publication period"""
        now = datetime.now()
        return now >= self.start_publication and now < self.end_publication

    @property
    def is_visible(self):
        """Check if an entry is visible on site"""
        return self.is_actual and self.status == PUBLISHED

    @property
    def related_published_set(self):
        """Return only related entries published"""
        return entries_published(self.related)

    @property
    def discussions(self):
        """Return published discussions"""
        return Comment.objects.for_model(self).filter(is_public=True)

    @property
    def comments(self):
        """Return published comments"""
        return self.discussions.filter(Q(flags=None) | Q(
            flags__flag=CommentFlag.MODERATOR_APPROVAL))

    @property
    def pingbacks(self):
        """Return published pingbacks"""
        return self.discussions.filter(flags__flag='pingback')

    @property
    def trackbacks(self):
        """Return published trackbacks"""
        return self.discussions.filter(flags__flag='trackback')

    @property
    def comments_are_open(self):
        """Check if comments are open"""
        if AUTO_CLOSE_COMMENTS_AFTER and self.comment_enabled:
            return (datetime.now() - self.start_publication).days < \
                   AUTO_CLOSE_COMMENTS_AFTER
        return self.comment_enabled

    @property
    def short_url(self):
        """Return the entry's short url"""
        return get_url_shortener()(self)

    def __unicode__(self):
        return '%s: %s' % (self.title, self.get_status_display())

    @models.permalink
    def get_absolute_url(self):
        """Return entry's URL"""
        return ('zinnia_entry_detail', (), {
            'year': self.creation_date.strftime('%Y'),
            'month': self.creation_date.strftime('%m'),
            'day': self.creation_date.strftime('%d'),
            'slug': self.slug})

    class Meta:
        abstract = True


def get_base_model():
    """Determine the base Model to inherit in the
    Entry Model, this allow to overload it."""
    if not ENTRY_BASE_MODEL:
        return EntryAbstractClass

    dot = ENTRY_BASE_MODEL.rindex('.')
    module_name = ENTRY_BASE_MODEL[:dot]
    class_name = ENTRY_BASE_MODEL[dot + 1:]
    try:
        _class = getattr(import_module(module_name), class_name)
        return _class
    except (ImportError, AttributeError):
        warnings.warn('%s cannot be imported' % ENTRY_BASE_MODEL,
                      RuntimeWarning)
    return EntryAbstractClass


class Entry(get_base_model()):
    """Final Entry model"""

    class Meta:
        """Entry's Meta"""
        ordering = ['-creation_date']

zinnia/views/sitemap.py
"""Views for Zinnia sitemap"""
from django.views.generic.simple import direct_to_template

from zinnia.models import Entry
from zinnia.models import Category


def sitemap(*ka, **kw):
    """Wrapper around the direct to template generic view to
    force the update of the extra context"""
    kw['extra_context'] = {'entries': Entry.published.all(),
                           'categories': Category.tree.all()}
    return direct_to_template(*ka, **kw)

zinnia/templates/zinnia/_entry_detail.html
{% load tagging_tags comments i18n %}

<div class="entry-header span-16 last">
  <h2 class="entry-title">
    <a href="{{ object.get_absolute_url }}" title="{{ object.title }}" rel="bookmark">
      {{ object.title }}
    </a>
  </h2>
  <p class="entry-info">
    {% if object.authors.count %}
    {% trans "Written by" %}
    {% for author in object.authors.all %}
    <span class="vcard author">
      <a href="{% url zinnia_author_detail author %}" class="fn nickname url" rel="author"
         title="{% blocktrans with author as author %}Show {{ author }} entries{% endblocktrans %}">{{ author }}</a>
    </span>{% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% trans "on" %}
    {% else %}
    {% trans "Written on" %}
    {% endif %}
    <abbr class="published" title="{{ object.creation_date|date:"c" }}Z">{{ object.creation_date|date:"DATE_FORMAT" }}</abbr>
    {% if object.categories.count %}
    {% trans "in" %}
    {% for category in object.categories.all %}
    <a href="{{ category.get_absolute_url }}" title="{{ category }}" rel="tag category">{{ category }}</a>{% if not forloop.last %}, {% endif %}{% endfor %}{% endif %}.
  </p>
</div>

<div class="entry-body span-16 last">
  {% if object.image %}
  <div class="entry-image">
    <p>
      <a href="{{ object.get_absolute_url }}" rel="bookmark">
	<img src="{{ object.image.url }}" alt="{{ object.title }}" class="left" />
      </a>
    </p>
  </div>
  {% endif %}
  <div class="entry-content">
    {{ object_content }}
  </div>
</div>

<div class="entry-footer">
  <p class="entry-tags span-16 last">
    <strong>{% trans "Tags" %}</strong> :
    {% tags_for_object object as tag_list %}
    {% for tag in tag_list %}
    <a href="{% url zinnia_tag_detail tag %}"
       title="Tag {{ tag }}" rel="tag">{{ tag }}</a>
    {% empty %}
    <span>{% trans "No tags" %}</span>
    {% endfor %}
  </p>

  <p class="entry-shorturl span-16 last">
    <strong>{% trans "Short url" %}</strong> :
    {% if object.short_url %}
    <a href="{{ object.short_url }}" title="{{ object.title }}" rel="shortlink">
      {{ object.short_url }}
    </a>
    {% else %}
    {% trans "Unavailable" %}
    {% endif %}
  </p>

  <p class="entry-comments span-16 last">
    <strong>{% trans "Discussions" %}</strong> :
    {% with object.comments.count as comment_count %}
    {% if comment_count %}
    <a href="{{ object.get_absolute_url }}#comments" title="{{ object.title }}">
      {% blocktrans count comment_count as comment_count %}{{ comment_count }} comment{% plural %}{{ comment_count }} comments{% endblocktrans %}
    </a>
    {% else %}
      {% if object.comments_are_open %}
      {% trans "No comments yet." %}
    <a href="{{ object.get_absolute_url }}#comments" title="{{ object.title }}">
      {% trans "Be first to comment!" %}
    </a>
      {% else %}
      {% trans "Comments are closed." %}
      {% endif %}
    {% endif %}
    {% endwith %}
    {% with object.pingbacks.count as pingback_count %}
    {% if pingback_count %}
    , <a href="{{ object.get_absolute_url }}#pingbacks" title="{{ object.title }}">
      {% blocktrans count pingback_count as pingback_count %}{{ pingback_count }} pingback{% plural %}{{ pingback_count }} pingbacks{% endblocktrans %}
    </a>
    {% endif %}
    {% endwith %}
    {% with object.trackbacks.count as trackback_count %}
    {% if trackback_count %}
    , <a href="{{ object.get_absolute_url }}#trackbacks" title="{{ object.title }}">
      {% blocktrans count trackback_count as trackback_count %}{{ trackback_count }} trackback{% plural %}{{ trackback_count }} trackbacks{% endblocktrans %}
    </a>
    {% endif %}
    {% endwith %}
  </p>
</div>

zinnia/templates/zinnia/author_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Author list" %}{% endblock %}

{% block title %}{% trans "Authors" %}{% endblock %}

{% block content %}
<h2>{% trans "Author list" %}</h2>
<div>
  <ul>
    {% for object in object_list %}
    <li class="vcard">
      <a href="{% url zinnia_author_detail object.username %}"
         title="{{ object.username }}" class="fn nickname url">
        {{ object.username }}
      </a>
      {% blocktrans count object.entries_published_set.count as entry_count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
    </li>
    {% endfor %}
  </ul>
</div>
{% endblock %}

zinnia/templates/zinnia/base.html
{% extends "zinnia/skeleton.html" %}
{% load zinnia_tags tagging_tags i18n %}

{% block meta %}
    <meta name="generator" content="Zinnia {{ ZINNIA_VERSION }}" />
{% endblock %}

{% block link %}
    <link rel="index" href="{% url zinnia_entry_archive_index %}" />
    <link rel="EditURI" type="application/rsd+xml" href="{% url zinnia_rsd %}" />
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url zinnia_wlwmanifest %}" />
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Blog" href="{% url zinnia_opensearch %}" />
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed of latest entries" %}" href="{% url zinnia_entry_latest_feed %}" />
    {% get_archives_entries "zinnia/tags/archives_entries_link.html" %}
{% endblock %}

{% block breadcrumbs %}
  {% zinnia_breadcrumbs %}
{% endblock %}

{% block sidebar %}
<div class="search">
  <h3>{% trans "Search" %}</h3>
  <form method="get" id="searchform" action="{% url zinnia_entry_search %}">
    <p>
      <input type="text" value="{% trans "Keywords..." %}" name="pattern" id="searchbox" onfocus="this.value=''"/>
      <input type="submit" class="submitbutton" value="OK" />
      <a title="{% trans 'You can use - to exclude words or phrases, &quot;double quotes&quot; for exact phrases and the AND/OR boolean operators combined with parenthesis for complex searchs.' %}">
        <img src="{{ ZINNIA_MEDIA_URL }}img/help.png" alt="?" width="14" height="14" />
      </a>
    </p>
  </form>
</div>
<div class="categories">
  <h3>{% trans "Categories" %}</h3>
  {% get_categories %}
</div>
<div class="authors">
  <h3>{% trans "Authors" %}</h3>
  {% get_authors %}
</div>
<div class="calendar">
  <h3>{% trans "Calendar" %}</h3>
  {% get_calendar_entries %}
</div>
<div class="tags">
  <h3>{% trans "Tags" %}</h3>
  {% tag_cloud_for_model zinnia.entry as tag_cloud with steps=6 %}
  <ul>
    {% for tag in tag_cloud %}
    <li>
      <a href="{% url zinnia_tag_detail tag.name %}" 
         title="{{ tag.count }} {% trans "entries" %}" 
         class="tag_{{ tag.font_size }}">{{ tag }}</a>
    </li>
    {% endfor %}
  </ul>
</div>
<div class="recents">
  <h3>{% trans "Recent entries" %}</h3>
  {% get_recent_entries 5 %}
</div>
<div class="comments">
  <h3>{% trans "Recent comments" %}</h3>
  {% get_recent_comments 5 %}
</div>
<div class="linkbacks">
  <h3>{% trans "Recent linkbacks" %}</h3>
  {% get_recent_linkbacks 5 %}
</div>
<div class="randoms">
  <h3>{% trans "Random entries" %}</h3>
  {% get_random_entries 5 %}
</div>
<div class="populars">
  <h3>{% trans "Popular entries" %}</h3>
  {% get_popular_entries 5 %}
</div>
<div class="archives">
  <h3>{% trans "Archives" %}</h3>
  {% get_archives_entries_tree %}
</div>
{% if user.is_authenticated %}
<div class="tools">
  <h3>{% trans "Tools" %}</h3>
  <ul>
    {% if perms.zinnia %}
    <li>
      <a href="{% url admin:app_list "zinnia" %}" title="{% trans "Dashboard" %}">
        {% trans "Dashboard" %}
      </a>
    </li>
    {% endif %}
    {% if perms.zinnia.add_entry %}
    <li>
      <a href="{% url admin:zinnia_entry_add %}" title="{% trans "Post an entry" %}">
        {% trans "Post an entry" %}
      </a>
    </li>
    {% endif %}
    {% block admin_tools %}
    {% endblock %}
    <li>
      <a href="{% url admin:logout %}" title="{% trans "Log out" %}">
        {% trans "Log out" %}
      </a>
    </li>
  </ul>
</div>
{% endif %}
{% endblock %}

zinnia/templates/zinnia/category_list.html
{% extends "zinnia/base.html" %}
{% load i18n mptt_tags %}

{% block meta-description %}{% trans "Category list" %}{% endblock %}

{% block title %}{% trans "Categories" %}{% endblock %}

{% block content %}
<h2>{% trans "Category list" %}</h2>
<div>
  {% for object, structure in object_list|tree_info %}
    {% if structure.new_level %}<ul><li>{% else %}</li><li>{% endif %}
      <a href="{{ object.get_absolute_url }}" title="{{ object }}">{{ object }}</a> 
      {% blocktrans count object.entries_published_set.count as entry_count %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}
      {% if object.description %}<br />{{ object.description|striptags|safe }}{% endif %}
    {% for level in structure.closed_levels %}</li></ul>{% endfor %}
  {% endfor %}
</div>
{% endblock %}

zinnia/templates/zinnia/entry_archive.html
{% extends "zinnia/entry_list.html" %}
{% load i18n zinnia_tags %}

{% block meta-description %}{% trans "Latest entries" %}{% endblock %}

{% block link %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="{{ ZINNIA_MEDIA_URL }}css/slider.css" />
{% endblock %}

{% block script %}
  {{ block.super }}
  <script type="text/javascript" src="{{ ZINNIA_MEDIA_URL }}js/jquery.js"></script>
  <script type="text/javascript" src="{{ ZINNIA_MEDIA_URL }}js/jquery.ui.js"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $("#slider").tabs({ fx:{ opacity: "toggle"}}).tabs("rotate", 5000, true);
      $("#slider").hover(
        function() { $("#slider").tabs("rotate", 0, true); },
        function() { $("#slider").tabs("rotate", 5000, true); });
    });
  </script>
{% endblock %}

{% block title %}{% trans "Latest entries" %}{% endblock %}

{% block content %}
{% get_featured_entries 5 "zinnia/tags/slider_entries.html" %}
{{ block.super }}
{% endblock %}

zinnia/templates/zinnia/entry_archive_day.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock %}

{% block title %}{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}{% endblock %}

{% block content %}
<h1>{% trans "Archives" %} {{ day|date:"DATE_FORMAT" }}</h1>

{{ block.super }}

<!--<ul>
  <li>
    <a href="{% url zinnia_entry_archive_day previous_day|date:"Y" previous_day|date:"m" previous_day|date:"d" %}" rel="archives">{{ previous_day|date:"DATE_FORMAT" }}</a>
  </li>
  {% if next_day %}
  <li>
    <a href="{% url zinnia_entry_archive_day next_day|date:"Y" next_day|date:"m" next_day|date:"d" %}" rel="archives">{{ next_day|date:"DATE_FORMAT" }}</a>
  </li>
  {% endif %}
</ul>-->
{% endblock %}

zinnia/templates/zinnia/entry_archive_month.html
{% extends "zinnia/entry_list.html" %}
{% load i18n %}

{% block meta-description %}{% trans "Archives" %} {{ month|date:"YEAR_MONTH_FORMAT" }}{% endblock %}

{% block title %}{% trans "Archives" %} {{ month|date:"YEAR_MONTH_FORMAT" }}{% endblock %}

{% block content %}
<h1>{% trans "Archives" %} {{ month|date:"YEAR_MONTH_FORMAT" }}</h1>

{{ block.super }}

<h2>{% trans "Daily archives" %}</h2>
<ul>
  {% for date in date_list %}
  <li>
    <a href="{% url zinnia_entry_archive_day date|date:"Y" date|date:"m" date|date:"d" %}" rel="archives">{{ date|date:"DATE_FORMAT" }}</a>
  </li>
  {% endfor %}
</ul>
<!--<ul>
  <li>
    <a href="{% url zinnia_entry_archive_month previous_month|date:"Y" previous_month|date:"m" %}" rel="archives">{{ previous_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% if next_month %}
  <li>
    <a href="{% url zinnia_entry_archive_month next_month|date:"Y" next_month|date:"m" %}" rel="archives">{{ next_month|date:"YEAR_MONTH_FORMAT" }}</a>
  </li>
  {% endif %}
</ul>-->
{% endblock %}

zinnia/templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n tagging_tags zinnia_tags %}

{% block meta-description %}{% trans "Latest entries for" %} {% if category %}{% trans "the category" %} {{ category }}{% if category.description %}: {{ category.description|striptags|safe }}{% endif %}{% endif %}{% if tag %}{% trans "the tag" %} {{ tag }}{% endif %}{% if author %}{% trans "the author" %} {{ author }}{% endif %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} {% trans "page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock %}

{% block link %}
  {{ block.super }}
  {% if category %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ category.title }}" href="{% url zinnia_category_feed category.tree_path %}" />
  {% endif %}
  {% if tag %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ tag.name }}" href="{% url zinnia_tag_feed tag.name %}" />
  {% endif %}
  {% if author %}
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS Feed" %} {{ author.username }}" href="{% url zinnia_author_feed author.username %}" />
  {% endif %}
{% endblock %}

{% block title %}{% trans "Latest entries" %} {% if category %}| {% trans "Category" %} {{ category }}{% endif %}{% if tag %}| {% trans "Tag" %} {{ tag }}{% endif %}{% if author %}| {% trans "Author" %} {{ author }}{% endif %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} | {% trans "Page" %} {{ page_obj.number }}{% endifnotequal %}{% endif %}{% endblock %}

{% block content %}
{% if category %}
<h1>{{ category.title }}</h1>
{% if category.description %}
<p>{{ category.description|striptags|safe }}</p>
{% endif %}
{% endif %}

{% if tag %}
<h1>{% trans "Tag" %} : {{ tag }}</h1>
{% endif %}

{% if author %}
<h1>{% blocktrans with author.username as author %}Entries by {{ author }}{% endblocktrans %}</h1>
{% endif %}

{% for object in object_list %}
<div id="entry-{{ object.pk }}" class="hentry{% if object.featured %} featured{% endif %} span-16 last">
  {% with object.html_content|truncatewords_html:100|safe as object_content %}
  {% include "zinnia/_entry_detail.html" %}
  {% endwith %}
</div>
<hr />
{% empty %}
  {% trans "No entries yet." %}
{% endfor %}

{% if is_paginated %}
<div class="paginator span-16 last">
  <span class="index">
    {% blocktrans with page_obj.number as current_page and paginator.num_pages as total_page %}Page {{ current_page }} of {{ total_page }}{% endblocktrans %}
  </span>
  {% if page_obj.has_previous %}
  <span class="previous">
    <a href="?page={{ page_obj.previous_page_number }}"
       title="{% trans "More recent entries" %}">&laquo;</a>
  </span>
  {% endif %}
  {% for page in paginator.page_range %}
  <span class="page {% ifequal page_obj.number page %}current{% endifequal %}">
    {% ifequal page_obj.number page %}
    <strong>{{ page }}</strong>
    {% else %}
    <a href="?page={{ page }}"
       title="{% trans "Entries page" %} {{ page }}">{{ page }}</a>
    {% endifequal%}
  </span>
  {% endfor %}
  {% if page_obj.has_next %}
  <span class="next">
    <a href="?page={{ page_obj.next_page_number }}"
       title="{% trans "More old entries" %}">&raquo;</a>
  </span>
  {% endif %}
</div>
{% endif %}
{% endblock %}

{% block admin_tools %}
  {% if category and perms.zinnia.change_category %}
  <li>
    <a href="{% url admin:zinnia_category_change category.pk %}" title="{% trans "Edit the category" %}">
      {% trans "Edit the category" %}
    </a>
  </li>
  {% endif %}
  {% if tag and perms.tagging.change_tag %}
  <li>
    <a href="{% url admin:tagging_tag_change tag.pk %}" title="{% trans "Edit the tag" %}">
      {% trans "Edit the tag" %}
    </a>
  </li>
  {% endif %}
  {% if author and perms.auth.change_user %}
  <li>
    <a href="{% url admin:auth_user_change author.pk %}" title="{% trans "Edit the author" %}">
      {% trans "Edit the author" %}
    </a>
  </li>
  {% endif %}
{% endblock %}

zinnia/templates/zinnia/login.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Login required" %}{% endblock %}

{% block content %}
<h2>{% trans "Login required" %}</h2>

<div class="entry_login">
  {% if form.errors %}
  <p class="error">
    {% trans "Your username and password didn't match. Please try again." %}
  </p>
  {% endif %}
  <p>
    {% trans "You need to be connected to view this entry." %}
  </p>

  <form method="post" action=".">
    {% csrf_token %}
    <table>
      <tr>
        <td>{{ form.username.label_tag }}</td>
        <td>{{ form.username }}</td>
      </tr>
      <tr>
        <td>{{ form.password.label_tag }}</td>
        <td>{{ form.password }}</td>
      </tr>
      <tr>
        <td colspan="2">
          <input type="hidden" name="next" value="." />
          <input type="submit" value="{% trans "Login" %}" />
        </td>
      </tr>
    </table>
  </form>
</div>
{% endblock %}